### ISSUE TITLE
Link output of qc to data ingest 

### ISSUE THREAD

**Issue by sgosline** [sgosline/srpAnalytics#6]

**Comment by sgosline** [comment]
Currently output of step 2 is written to the local file path, and we need to find a way to pass in the files to step three. I will work on this either by making step 2 a function of the wrapper, or writing them to a pre-annotated directory.

**Comment by sgosline** [comment]
I didn't file a pull request but got this in the latest repo. Had to move around some files. Will do one last cleanup of the repo.

**Comment by kimdn** [comment]
> I didn't file a pull request but got this in the latest repo. Had to move around some files. Will do one last cleanup of the repo.

Ok, sounds good to me. With my 2 times of experience of working with other developers (50 and 20 people each), people who frequently commit to master branch has less problem of merging. On the other hand, people who infrequently commit to master br need to spend some time to resolve conflicts and pass unit test. I want to say that please feel free to commit to main (master) branch by yourself to speed up for you and your portal development team. My changes are mostly small number of files, so I can adapt to main branch later relatively easily. Additionally, I am removing duplicated files/functions of Paritosh so that we can maintain code easily.
